/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.motorph.payroll.ui;

import com.motorph.payroll.models.Employee; 
import com.motorph.payroll.models.FullTimeEmployee;
import com.motorph.payroll.models.PartTimeEmployee;
import com.motorph.payroll.payroll.PayrollProcessor;
import javax.swing.*;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
/**
 *
 * @author samleonor
 */
public class PayslipFrame extends javax.swing.JFrame {
    private Employee employee;
    private PayrollProcessor payrollProcessor;

    public PayslipFrame(Employee employee) {
        this.employee = employee;
        this.payrollProcessor = new PayrollProcessor(employee);

        setTitle("Employee Payslip");
        setSize(450, 400);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);

        initComponents();  
        loadPayslipDetails(); 
    }

    /**
     * Creates new form PayslipFrame
     */
    public PayslipFrame() {
        initComponents();
    }
    
    private void loadPayslipDetails() {
        lblEmployeeName.setText(employee.getFirstName() + " " + employee.getLastName());
        lblEmployeeID.setText(employee.getEmployeeId());

        // Determine Full-Time or Part-Time Employee
        if (employee instanceof FullTimeEmployee) {
            lblPosition.setText("Full-Time");
        } else if (employee instanceof PartTimeEmployee) {
            lblPosition.setText("Part-Time");
        } else {
            lblPosition.setText("Unknown");
        }

        lblBasicSalary.setText("₱" + String.format("%,.2f", employee.getSalary()));
        lblOvertimePay.setText("₱" + String.format("%,.2f", payrollProcessor.calculateOvertimePay()));
        lblAllowances.setText("₱2,000"); // Assuming fixed allowance
        lblDeductions.setText("₱" + String.format("%,.2f", payrollProcessor.calculateDeductions()));
        lblNetPay.setText("₱" + String.format("%,.2f", payrollProcessor.calculateNetSalary()));
    }
    
    private void exportPayslip() {                                              
        if (employee == null) {
            JOptionPane.showMessageDialog(this, "No employee data available to export!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String filename = employee.getEmployeeId() + "_Payslip.txt";
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(filename))) {
            writer.write("Payslip for " + employee.getFirstName() + " " + employee.getLastName() + "\n");
            writer.write("===================================\n");
            writer.write("Employee ID: " + employee.getEmployeeId() + "\n");
            writer.write("Position: " + lblPosition.getText() + "\n");
            writer.write("Basic Salary: " + lblBasicSalary.getText() + "\n");
            writer.write("Overtime Pay: " + lblOvertimePay.getText() + "\n");
            writer.write("Allowances: " + lblAllowances.getText() + "\n");
            writer.write("Deductions: " + lblDeductions.getText() + "\n");
            writer.write("Net Pay: " + lblNetPay.getText() + "\n");
            writer.write("===================================\n");

            JOptionPane.showMessageDialog(this, "✅ Payslip exported successfully! Saved as: " + filename, "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "❌ Error exporting payslip!", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblEmployeeName = new javax.swing.JLabel();
        lblEmployeeID = new javax.swing.JLabel();
        lblPosition = new javax.swing.JLabel();
        lblBasicSalary = new javax.swing.JLabel();
        lblOvertimePay = new javax.swing.JLabel();
        lblAllowances = new javax.swing.JLabel();
        lblDeductions = new javax.swing.JLabel();
        lblNetPay = new javax.swing.JLabel();
        lblNameLabel = new javax.swing.JLabel();
        lblEmployeeIDLabel = new javax.swing.JLabel();
        lblPositionLabel = new javax.swing.JLabel();
        lblBasicSalaryLabel = new javax.swing.JLabel();
        lblOvertimePayLabel = new javax.swing.JLabel();
        lblAllowancesLabel = new javax.swing.JLabel();
        lblDeductionsLabel = new javax.swing.JLabel();
        lblNetPayLabel = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        btnExportPayslip = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setText("Employee Payslip");

        lblEmployeeName.setText("Name:");

        lblEmployeeID.setText("Employee ID:");

        lblPosition.setText("Position:");

        lblBasicSalary.setText("Basic Salary:");

        lblOvertimePay.setText("Overtime Pay:");

        lblAllowances.setText("Allowances:");

        lblDeductions.setText("Deductions:");

        lblNetPay.setText("Net Pay:");

        lblNameLabel.setText("jLabel10");

        lblEmployeeIDLabel.setText("jLabel11");

        lblPositionLabel.setText("jLabel12");

        lblBasicSalaryLabel.setText("jLabel13");

        lblOvertimePayLabel.setText("jLabel14");

        lblAllowancesLabel.setText("jLabel15");

        lblDeductionsLabel.setText("jLabel16");

        lblNetPayLabel.setText("jLabel17");

        btnPrint.setText("Print");

        btnExportPayslip.setText("Export Payslip");

        btnClose.setText("Close");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTitle)
                        .addGap(126, 126, 126))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmployeeName)
                            .addComponent(lblNetPay)
                            .addComponent(lblDeductions)
                            .addComponent(lblAllowances)
                            .addComponent(lblOvertimePay)
                            .addComponent(lblBasicSalary)
                            .addComponent(lblPosition)
                            .addComponent(lblEmployeeID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNameLabel)
                            .addComponent(lblEmployeeIDLabel)
                            .addComponent(lblPositionLabel)
                            .addComponent(lblBasicSalaryLabel)
                            .addComponent(lblOvertimePayLabel)
                            .addComponent(lblAllowancesLabel)
                            .addComponent(lblDeductionsLabel)
                            .addComponent(lblNetPayLabel))
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnPrint)
                        .addGap(18, 18, 18)
                        .addComponent(btnExportPayslip)
                        .addGap(18, 18, 18)
                        .addComponent(btnClose)))
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblTitle)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeName)
                    .addComponent(lblNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeID)
                    .addComponent(lblEmployeeIDLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPosition)
                    .addComponent(lblPositionLabel))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBasicSalary)
                    .addComponent(lblBasicSalaryLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOvertimePay)
                    .addComponent(lblOvertimePayLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAllowances)
                    .addComponent(lblAllowancesLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeductions)
                    .addComponent(lblDeductionsLabel))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNetPay)
                    .addComponent(lblNetPayLabel))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrint)
                    .addComponent(btnExportPayslip)
                    .addComponent(btnClose))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String[] args) { 
        SwingUtilities.invokeLater(() -> {
            FullTimeEmployee testEmployee = new FullTimeEmployee("10001", "Manuel III", "Garcia", "Makati City", "966-860-270", 90000);
            new PayslipFrame(testEmployee).setVisible(true);
        });
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnExportPayslip;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel lblAllowances;
    private javax.swing.JLabel lblAllowancesLabel;
    private javax.swing.JLabel lblBasicSalary;
    private javax.swing.JLabel lblBasicSalaryLabel;
    private javax.swing.JLabel lblDeductions;
    private javax.swing.JLabel lblDeductionsLabel;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblEmployeeIDLabel;
    private javax.swing.JLabel lblEmployeeName;
    private javax.swing.JLabel lblNameLabel;
    private javax.swing.JLabel lblNetPay;
    private javax.swing.JLabel lblNetPayLabel;
    private javax.swing.JLabel lblOvertimePay;
    private javax.swing.JLabel lblOvertimePayLabel;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JLabel lblPositionLabel;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
